---
- name: Configurar servidores
  hosts: servers
  become: yes
  tasks:
    - name: Actualizar cache de apt
      apt:
        update_cache: yes

    - name: Instalar apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear archivo
      file:
        path: /home/vagrant/archivo.txt
        state: touch

    - name: Copiar archivos
      copy:
        src: /path/to/local/file.txt
        dest: /home/vagrant/destino.txt

    - name: Crear carpetas
      file:
        path: /home/vagrant/nueva_carpeta
        state: directory

    - name: Iniciar el servicio apache2
      service:
        name: apache2
        state: started

    - name: Agregar usuario
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar un script
      command: /home/vagrant/script.sh
